#!/usr/bin/env node
'use strict';

/**
 * Generates src/environments/environment.ts from .env. Angular's build/
 * serve/test builders don't read .env files natively, so this script is
 * the bridge: it runs before every build/start/test/watch (see the pre*
 * hooks in package.json) and writes a plain TS module the app imports
 * as `@env`.
 *
 * The generated file is gitignored (it can contain real n8n webhook
 * secrets) - only .env.example, with blank/placeholder values, is
 * committed. Copy .env.example to .env and fill in the real values
 * before building/serving/testing locally.
 *
 * No dependency (e.g. dotenv) is used on purpose, to keep the surface
 * this script pulls into the build small - this only needs to parse
 * simple KEY=VALUE lines.
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const outDir = path.join(rootDir, 'src', 'environments');
const outPath = path.join(outDir, 'environment.ts');

/** Minimal KEY=VALUE parser - comments (#) and blank lines are skipped, values may be quoted. */
function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const result = {};
  const content = fs.readFileSync(filePath, 'utf8');

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const eqIndex = line.indexOf('=');
    if (eqIndex === -1) {
      continue;
    }

    const key = line.slice(0, eqIndex).trim();
    let value = line.slice(eqIndex + 1).trim();
    const isQuoted =
      (value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"));
    if (isQuoted) {
      value = value.slice(1, -1);
    }

    result[key] = value;
  }

  return result;
}

const parsed = parseEnvFile(envPath);
// Real environment variables (e.g. set by CI) win over .env, matching
// how most .env tooling behaves.
const env = { ...parsed, ...process.env };

const REQUIRED_VARS = [
  'API_BASE_URL',
  'N8N_WEBHOOK_URL',
];

const missing = REQUIRED_VARS.filter((name) => !env[name]);
if (missing.length > 0) {
  console.error(
    `[generate-env] Missing required variable(s): ${missing.join(', ')}.\n` +
      '[generate-env] Copy .env.example to .env and fill in the real values, then try again.',
  );
  process.exit(1);
}

function jsString(value) {
  return JSON.stringify(value);
}

const environmentTs = `// AUTO-GENERATED by scripts/generate-env.js from .env - do not edit by
// hand, and never commit this file (see .gitignore). Re-run
// \`npm run env:generate\` after changing .env, or just use
// \`npm start\` / \`npm run build\` / \`npm test\`, which regenerate it
// for you via the pre* hooks in package.json.
export const environment = {
  apiBaseUrl: ${jsString(env.API_BASE_URL)},
  n8nWebhookUrl: ${jsString(env.N8N_WEBHOOK_URL)},
};
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, environmentTs);
console.log('[generate-env] Wrote src/environments/environment.ts from .env');
